<?php


namespace app\model;

use app\interfaces\ICart;

class Cart extends Model implements ICart
{
    public $id;
    public $user_id;
    public $products = [];

    protected $productsAmount;
    protected $sum;

    public function __construct($user_id)
    {
        parent::__construct();
        $this->user_id = $user_id;
        $this->products[] = $this->getWhere("user_id", $this->user_id);

    }

    public function save()
    {
        return parent::save(); // TODO: Change the autogenerated stub
    }

    public function add($id) {
        // INSERT || UPDATE
        die;
    }

    public function removeOne($id) {
        // UPDATE || DELETE
        die;
    }

    public function removeAll($id) {
        // DELETE
        die;
    }

    protected function getSum() {
        die;
    }
}
